### ISSUE TITLE
aot error

### ISSUE THREAD

**Issue by vgflutter** [valor-software/ngx-bootstrap#1551]
Hi, I use angular-cli 1.0.0 beta 21 with angular 2.2.1 and ng2-bootstrap  1.2.1
I have ng2-bootstrap but doesn't use it.
I have created tsconfig-aot.json and run:

$ ../node_modules/.bin/ngc -p tsconfig-aot.json
can't resolve module node_modules/ng2-bootstrap/utils/linked-list.class.d.ts from node_modules/ng2-bootstrap/utils/linked-list.class.d.ts
Error: can't find symbol LinkedList exported from module 

can you help me ?

**Comment by valorkin** [comment]
there are were couple of such issues, they all were fixed in 1.3.0

**Comment by vgflutter** [comment]
Hi, i take this opportunity to a another question. I have updated ng2-boostrap and I have this problem:
node_modules/.bin/ngc -p src/tsconfig-aot.json

Type CollapseDirective in .../node_modules/ng2-bootstrap/collapse/collapse.directive.d.ts is part of the declarations of 2 modules: CollapseModule in ...node_modules/ng2-bootstrap/collapse/collapse.module.d.ts.and AppModule in .../src/app/app.module.ts! Please consider moving CollapseDirective in ...node_modules/ng2-bootstrap/collapse/collapse.directive.d.ts to a higher module that imports CollapseModule in ...node_modules/ng2-bootstrap/collapse/collapse.module.d.ts and AppModule in /Users/vincenzo/Documents/work/Hello2/src/app/app.module.ts....

I have no idea what it means.
I use only CollapseDirective in app.modules

import { CollapseDirective } from 'ng2-bootstrap'

@NgModule({
  declarations: [
    CollapseDirective

Help me Tnx!

**Comment by jlberrocal** [comment]
@valorkin i installed version 1.3.1 and i'm still getting the error that @feof mentioned on first comment, just in case i deleted my node_modules folder and install all again

**Comment by valorkin** [comment]
No-no, you should import collapse module, like in doc
