### ISSUE TITLE
Style not working on tabs

### ISSUE THREAD

**Issue by jdeblander** [valor-software/ngx-bootstrap#1698]
I have the following setup:

 ```
<tabset>
    <tab customClass="tab-style">
        <template tabHeading>
            Tab1
        </template>
        <div class="tab-page-content">
            <!-- content-->
        </div>
    </tab>
    <tab customClass="tab-style">
        <template tabHeading>
            Tab2
        </template>
        <div class="tab-page-content">
            <!-- content-->
        </div>
    </tab>
<tabset>
```

And my styling is:

```
.tab-style {
    background-color: red;
}
// other styling
```

Now it seems that the customClass "tab-style" is correctly set on the "li" element, but the styling doesn't seem to work at all.

Picture:
http://imgur.com/a/wLk3f

**Comment by valorkin** [comment]
this should help: http://valor-software.com/ng2-bootstrap/#/tabs#styling

**Comment by myeung58** [comment]
+1 not working

In my case it'd work if the styling are set in the global styles.css file, but not when they're set inside the component's own style file. Could be something related to angular's css encapsulation.

existing issue: #1410

**Comment by jdeblander** [comment]
Well I simplified my code to the following:

```
<tabset>
   <tab heading="Tab1" customClass="tab-style">
       <div class="tab-page-content">
           <!-- content-->
       </div>
   </tab>
   <tab heading="Tab2" customClass="tab-style">
       <div class="tab-page-content">
           <!-- content-->
       </div>
   </tab>
<tabset>
```

And I've tried putting styling in de css of te component and in the css of my app aswell.
Both doesn't change a thing.

I've been looking carefully at the docs, but I can't spot any possible mistake at the moment.

**Comment by jdeblander** [comment]
It seems my issue is solved, but I can't really explain how.
I'd read a little more about the CSS encapsulation of Angular2 and decided to test some things.
 I added `ViewEncapsulation.None` to my component who's containing the tabset and it seemed that the styling then worked correctly.
But the change broke some other things, so I removed the line again from the component. And to my surprise, the styling kept working. Still my code looks exactly the same as mentioned before.

I'm not sure what has been triggered end why the problem is suddenly fixed. At least it doens't seem to be a problem with your provided component. Thanks for the help anyways and for providing the Angular components.

**Comment by valorkin** [comment]
Awesome, glad to hear.:)

**Comment by Captnwalker1** [comment]
This is still an issue, should not have to set ViewEncapsulation to None, that will definitely break some other things.


Its caused by the outputted html not having the _ngcontent attribute for the component 

```
<tabset _ngcontent-ahn-19="" class="tabs checkout-tabs tab-container" ng-reflect-justified="true">
    <ul class="nav nav-justified nav-tabs" ng-reflect-klass="nav" ng-reflect-ng-class="[object Object]">
        <li ng-reflect-ng-class="nav-item,tab" class="nav-item tab">
          <a class="nav-link" href="javascript:void(0);">
            <span>Log in</span>
          </a>
        </li>
        <li ng-reflect-ng-class="nav-item," class="nav-item active">
          <a class="nav-link active" href="javascript:void(0);">
            <span>Checkout as Guest</span>
          </a>
        </li>
    </ul>
  </tabset>
```

The encapsulation for a component always appends that _ng_content to generated css:
```
.checkout-tabs[_ngcontent-ahn-19] > ul[_ngcontent-ahn-19] > li[_ngcontent-ahn-19] { background: red !important; }
```

So without the _ngcontent attribute appended to the generated tab elements the CSS won't match.

**Comment by dpereverzev** [comment]
@Captnwalker1 @Tommytoe  that is how angular works with styles. You can reach your purpose via using special selectors such as :host /deep/ .
`:host /deep/ .tab-style {
  background-color: red;
}`
but be careful of using /deep/. It has deprecated status.
More: https://www.chromestatus.com/features/6750456638341120

**Comment by jdeblander** [comment]
Yep, using `:host /deep/ .some-class { /* styling*/ } ` works for me.
This syntax is deprecated in Chrome, but [Angular](https://angular.io/docs/ts/latest/guide/component-styles.html#) has is own version, using `ViewEncapsulation.Emulated`, which is the default ViewEncapsulation.

Also a small hint for those who are using VS Code. The` /deep/` syntax will be supported in the **April** release (1.12+).

**Comment by RezaRahmati** [comment]
This is still an issue, and investigation shows that @Captnwalker1 is correct, li items doesnt have  _ng_content atribute

**Comment by jrymer** [comment]
Still having this issue. Any chance of this being fixed?

Can you force _ng_content on an attribute?

**Comment by devfomichov** [comment]
Hi, @Tommytoe ! If using angular, you need add style.css in .angular-cli.json
![cli](https://user-images.githubusercontent.com/11698048/28497686-a3d87520-6f95-11e7-8b3c-58485e598cd2.PNG)
 and add you class in style.css.
![style](https://user-images.githubusercontent.com/11698048/28497690-b0c8eac6-6f95-11e7-9175-e01144ccfeff.PNG)
 After you was complete this stage you need add you custom class in tabs component.
![html](https://user-images.githubusercontent.com/11698048/28497692-ba218be6-6f95-11e7-905b-0e3ad63110f6.PNG)
Result :)
![result](https://user-images.githubusercontent.com/11698048/28497713-f536f95a-6f95-11e7-8955-793c7edd1bb9.PNG)

**Comment by shurvirmori** [comment]
+1 not working....
My `customclass` is adding in both, `<li class="nav-item">` and `<tab>`
and it effects in `<tab></tab>` but not in main `<li>`.

![image](https://user-images.githubusercontent.com/15141789/31992568-4741f186-b998-11e7-859f-81885af7c91f.png)

**Comment by alireza-saberi** [comment]
I had a same issue, but after reading all of above comments, I was able to work around and resolve my issue.
Here is what I have and what I see for this specific component.
- I have bootstrap-sass in my project, and I am overriding it.
- If I try to override tabs on the component css file or style.scss, it wont work, but when I introduce a new rule like `.tab-style {
    background-color: red;
}`, it works since there in no bootstrap rule for it.

**Workaround**:
- Since I am overriding bootstrap-sas library in my project to have my personal theme. I created a new `_nave.scss` where I override bootstrap-sass, and I put all overriding rules in it. 

It works! :sparkles:
ps: as a side note: I dont understand why overriding bootstrap rule on the component style file, and style.scss dont answer.

**Comment by northoutIshan** [comment]
@jdeblander 
I think you are not using single quotes for using class name
`<tabset>
   <tab customClass="'tab-style'">
             required code...
   </tab>
<tabset>`

**Comment by ortmann64** [comment]
I resolved it like this:

Inside the ".angular-cli.json" under "styles" you have to put "styles.scss" after "bootstrap.css" so it can override the class of bootstrap.

<img width="617" alt="bildschirmfoto 2018-01-06 um 12 06 33" src="https://user-images.githubusercontent.com/17614249/34639179-eeaea222-f2da-11e7-9c94-7d74fa534e56.png">

and then you can set the colors of the tabs like this:

```
.nav-tabs .nav-link.active, .nav-tabs .nav-item.show .nav-link {
  color: black;
  background-color: red;
}

.nav-tabs .nav-link, .nav-tabs .nav-item.show .nav-link {
  color: white;
  background-color: blue;
}
```

**Comment by jechazelle** [comment]
If you want to overriding bootstrap rule on the component style file, add this on your component

> encapsulation: ViewEncapsulation.None

```
import {ViewEncapsulation} from '@angular/core';

@Component({
  selector: 'app',
  styleUrls: ['./bootstrap.scss'],
  encapsulation: ViewEncapsulation.None,
  ...
})
```

[https://github.com/gdi2290/angular-starter/wiki/How-to-include-SCSS-in-components](https://github.com/gdi2290/angular-starter/wiki/How-to-include-SCSS-in-components)

**Comment by danielptm** [comment]
@jechazelle solution worked for me to change the color of the text of the tab I did this.

`Component
@Component({
  selector: 'app-edit-center',
  templateUrl: './edit-center.component.html',
  styleUrls: ['./edit-center.component.sass'],
  encapsulation: ViewEncapsulation.None
})

css
.tab-style > a
  :color green

html
<tab customClass="tab-style" heading="About" id="tab1">`

**Comment by felipevegners** [comment]
@jechazelle it works for me, thanks!

**Comment by majorsaaam** [comment]
@jechazelle Also works for me. Thanks.

It's extremely inconvenient to be unable to style tabs as easy as the documentation suggests. Why this isn't considered a bug?

**Comment by skyzito** [comment]
Works for me too.

**Comment by abhishekalai** [comment]
Either a bug, or include adding `encapsulation: ViewEncapsulation.None` to the component.ts in Docs.
@jechazelle 's answer worked for me

**Comment by abbhishek971** [comment]
Either a bug, or include adding `encapsulation: ViewEncapsulation.None` to the component.ts in Docs.
@jechazelle 's answer worked for me

**Comment by Akshat0102** [comment]
1. If we use `encapsulation: ViewEncapsulation.None` in our component file then using a style changes like `.nav-link.disabled, .nav-link:disabled { color: white; }` or `.nav-link {background-color: green}` works but making **ViewEncapsulaion as None** means making the styles of that component global which may affect the styles of your other components.

2. If we use customClass property of tab inside tabset like `<tab customClass="custom-tab-style">` and then using global style file which is styles.scss in your root folder (.src) like` .custom-tab-style{ .nav-link.disabled, .nav-link:disabled{ color: white; } } ` will work fine without needing to set ViewEncapsulation as None and it will also not affect any other component style as long as the class name is unique.
