### ISSUE TITLE
Can't resolve moment

### ISSUE THREAD

**Issue by maraymer** [valor-software/ngx-bootstrap#2386]
Hello,

After a recent update to my project setup and encountered an error I hadn't seen previously which is preventing me from loading the project via ng serve.

ERROR in /node_modules/ngx-bootstrap/datepicker2/common/bs-date-picker-state.provider.d.ts (2,25): Cannot find module 'moment'.

ERROR in /node_modules/ngx-bootstrap/datepicker2/common/bs-date-picker-options.provider.d.ts (1,25): Cannot find module 'moment'.

ERROR in /node_modules/ngx-bootstrap/datepicker2/common/bs-date-picker-base.class.d.ts (3,25): Cannot find module 'moment'.

ERROR in /node_modules/ngx-bootstrap/datepicker2/current-date/bs-current-date.component.d.ts (5,25): Cannot find module 'moment'.

ERROR in /node_modules/ngx-bootstrap/datepicker2/custom-range/bs-custom-range-picker.component.d.ts (4,25): Cannot find module 'moment'.

ERROR in /node_modules/ngx-bootstrap/datepicker2/month/bs-month-picker.component.d.ts (4,25): Cannot find module 'moment'.

ERROR in /node_modules/ngx-bootstrap/datepicker2/time/bs-date-time-picker.component.d.ts (5,25): Cannot find module 'moment'.

ERROR in /src/app/app.module.ts (58,34): Argument of type 'Http' is not assignable to parameter of type 'HttpClient'.
  Property 'handler' is missing in type 'Http'.

ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 118:19 in the original .ts file), resolving symbol AppModule in /src/app/app.module.ts

ERROR in ./~/ngx-bootstrap/datepicker/date-formatter.js
Module not found: Error: Can't resolve 'moment' in '/node_modules/ngx-bootstrap/datepicker'
 @ ./~/ngx-bootstrap/datepicker/date-formatter.js 1:0-28
 @ ./~/ngx-bootstrap/datepicker/index.js
 @ ./~/ngx-bootstrap/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ngx-bootstrap/datepicker2/custom-range/bs-custom-range-picker.component.js
Module not found: Error: Can't resolve 'moment' in '/node_modules/ngx-bootstrap/datepicker2/custom-range'
 @ ./~/ngx-bootstrap/datepicker2/custom-range/bs-custom-range-picker.component.js 15:0-33
 @ ./~/ngx-bootstrap/datepicker2/index.js
 @ ./~/ngx-bootstrap/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ngx-bootstrap/datepicker2/current-date/bs-current-date.component.js
Module not found: Error: Can't resolve 'moment' in '/node_modules/ngx-bootstrap/datepicker2/current-date'
 @ ./~/ngx-bootstrap/datepicker2/current-date/bs-current-date.component.js 16:0-33
 @ ./~/ngx-bootstrap/datepicker2/index.js
 @ ./~/ngx-bootstrap/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ngx-bootstrap/datepicker2/year/bs-year-picker.component.js
Module not found: Error: Can't resolve 'moment' in '/node_modules/ngx-bootstrap/datepicker2/year'
 @ ./~/ngx-bootstrap/datepicker2/year/bs-year-picker.component.js 15:0-33
 @ ./~/ngx-bootstrap/datepicker2/index.js
 @ ./~/ngx-bootstrap/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-state.provider.js
Module not found: Error: Can't resolve 'moment' in '/node_modules/ngx-bootstrap/datepicker2/common'
 @ ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-state.provider.js 12:0-33
 @ ./~/ngx-bootstrap/datepicker2/index.js
 @ ./~/ngx-bootstrap/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ngx-bootstrap/datepicker2/day/bs-day-picker.component.js
Module not found: Error: Can't resolve 'moment' in '/node_modules/ngx-bootstrap/datepicker2/day'
 @ ./~/ngx-bootstrap/datepicker2/day/bs-day-picker.component.js 15:0-33
 @ ./~/ngx-bootstrap/datepicker2/index.js
 @ ./~/ngx-bootstrap/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ngx-bootstrap/datepicker2/time/bs-date-time-picker.component.js
Module not found: Error: Can't resolve 'moment' in '/node_modules/ngx-bootstrap/datepicker2/time'
 @ ./~/ngx-bootstrap/datepicker2/time/bs-date-time-picker.component.js 24:0-33
 @ ./~/ngx-bootstrap/datepicker2/index.js
 @ ./~/ngx-bootstrap/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts

ERROR in ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-base.class.js
Module not found: Error: Can't resolve 'moment' in '/node_modules/ngx-bootstrap/datepicker2/common'
 @ ./~/ngx-bootstrap/datepicker2/common/bs-date-picker-base.class.js 2:0-33
 @ ./~/ngx-bootstrap/datepicker2/custom-range/bs-custom-range-picker.component.js
 @ ./~/ngx-bootstrap/datepicker2/index.js
 @ ./~/ngx-bootstrap/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts
webpack: Failed to compile.

Anyone have any ideas?

**Comment by IlyaSurmay** [comment]
Which version of ngx-bootstrap are you using? There was an issue with moment in 2.0.0-beta.2 and it was fixed in 2.0.0-beta.3

**Comment by maraymer** [comment]
@IlyaSurmay Ah!  It appears I'm still using beta.2  I'll try updating and get back to you.

**Comment by maraymer** [comment]
@IlyaSurmay no luck.  Still the same after updating to beta.3

**Comment by IlyaSurmay** [comment]
This might be a silly advice, but try to reinstall node_modules. If this won't help, please create a sample repo and I'll take a look

**Comment by 7185** [comment]
I ran into the same issue and I'm pretty sure the fix was committed (4cd0e4a) **after** the 2.0.0-beta.3 release (5c003d1) .
So I guess it will be fixed in the 2.0.0-beta.4 release. Installing moment manually solved it for me.

**Comment by maraymer** [comment]
@IlyaSurmay thanks but I did delete and reinstall :-)
Doing the manual install seems to have resolved the problem.
