### ISSUE TITLE
Manually setting DatePicker value returns "Invalid Date" when date format is MMM D, YYYY

### ISSUE THREAD

**Issue by bamanuel** [valor-software/ngx-bootstrap#4213]
### Bug description:

Given the date format is set to `MMM D, YYYY`, manually entering "Mar 31, 2018" sets value to "Invalid Date". And entering "Feb 25, 2018" sets value to "Sun Mar 25 2018 00:00:00"

The issue actually came up when unit test started failing since value is updated programattically through `inputElement.value = moment(TEST_DATE).format(FORMAT);`

### Plunker that reproduces the issue:

Plunkr: https://plnkr.co/edit/AKw71bGCflab51uVJZcv

### Versions of ngx-bootstrap, Angular, and Bootstrap:

ngx-bootstrap: 2.0.3

Angular: 4.4.6

Bootstrap: 3.3.7

### Build system: Angular CLI, System.js, webpack, starter seed:

Webpack: 2.6.1

**Comment by ctrl-brk** [comment]
Yeah, it looks like the datepicker moves entered value one month ahead when losing focus. And since there's no April 31st it's throwing an error.

**Comment by mahendra94us** [comment]
I have created a datepicker field to display date in format JAN/01/208 and given dataInputFormat as MMM/DD/YYYY.  For example:
<input type="text" class="form-control text-left  input-margin" id="successorHolderDateOfBirth" name="dateOfBirth"
placeholder="test"
bsDatepicker formControlName="dateOfBirth" [bsConfig]="{ dateInputFormat: 'MMM/DD/YYYY' }"  [attr.value]="successorHolderForm.controls.dateOfBirth.value">

Here dateOfBirth is a FormControl. 

When I select a date from poped up calendar, date is populated in the text box and on tab out of field also date is consistent.

However, when I update any value in the text box manually, for example change the year and tab out of the field, the month is automatically increased. For example:
If date in text field I filled as Jan/01/2018 and tab out then text field month increase automatically.
For example:  Jan/01/2018  changes to Feb/01/2018 automatically on tab out from the field.

This issue is not happening if date format is  MM/DD/YYYY but this issue happening if date format is MMM/DD/YYYY'.

Please suggest.

**Comment by clabnet** [comment]
Similar problem . See https://stackblitz.com/edit/ngx-bootstrap-bsdatepicker-bug for error use-case.

**Comment by Oowaay** [comment]
Nothing new about this issue ?

**Comment by jmichaud-ips** [comment]
I'm having the same problem when I use the MMMM D YYYY format, when I manually type the month, and then leave, month is incremented by one. I have the same problem on a reactive template and template driven. I do NOT see the same problem on the documentation page. I even tried using the same format the documentation page is using for dateInputFormat: MMMM Do YYYY,h:mm:ss a.  I'm using ngx-bootstrap version 2.0.5 and Angular version 5.2.10.

**Comment by daniloff200** [comment]
I think, that was fixed in https://github.com/valor-software/ngx-bootstrap/pull/5376 , but, need to check all the use cases

**Comment by kumarl1** [comment]
Still facing the same issue with bootstrap version 5 when we are using DD MMM YYYY format. please check
