### ISSUE TITLE
Uncaught (in promise): Template parse errors:No Provider for NgModel

### ISSUE THREAD

**Issue by mshahin364** [valor-software/ngx-bootstrap#638]
Can anybody help me to solve this following error. I am using webpack. 

**Error: Uncaught (in promise): Template parse errors:
No provider for NgModel ("String() }}</alert>
            <div style="display:inline-block; min-height:290px;">
              [ERROR ->]<datepicker [(ngModel)]="date" showWeeks="true"></datepicker>
            </div>**

**Comment by Dinistro** [comment]
Do you use @angular/forms? Because they are not supported right now until this is merged: #631

**Comment by mshahin364** [comment]
Yes, i am using @angular/forms.

**Comment by Dinistro** [comment]
@mshahin364 They are currently not supported. Wait for this PR: #631

**Comment by AndersonDev** [comment]
Waiting to PR: #631 !!! Update as soon as posible please

**Comment by orkisz** [comment]
@Dinistro I have the same issue. I'm using angular 2.0.0-rc.4 and angular/forms 0.2.0. Is there any possibility to get it working without waiting for PR?

**Comment by Dinistro** [comment]
@orkisz It was merged in another PR. Unfortunately it's currently not released, but @valorkin is working on it. 

But you can clone the actual version and install it, then do a npm run flow.compile and an npm link. Finally you need to switch in your project and run npm link ng2-bootstrap. This should create a symlink in the `node_modules`-folder that points to the cloned repo. 

Note: I had not enough time to try this out, but I think it works.

**Comment by orkisz** [comment]
@Dinistro I tried to build actual version, but it fails at `flow.compile:system` step with message:
`

> ng2-bootstrap@1.0.17 flow.compile:system C:\Users\xxx\WORKS\ng2-bootstrap
> ./.config/bundle-system.js`
> '.' is not recognized as an internal or external command,
> operable program or batch file.

I use windows environment, could it be a cause of problem?
When manually invoking "node .config\config.bundle.js" i get:
`

> node .config\bundle-system.js
> Deleted files and folders:
> Bundling system.js file: ng2-bootstrap.js { minify: false, sourceMaps: true, mangle: false }
> Unhandled rejection Error on fetch for C:\Users\xxx\WORKS\ng2-bootstrap\node_modules\rxjs/add/observable/from at file:///C:/Users/xxx/WORKS/C:\Users\xxx\WORKS\ng2-bootstrap\node_modules\rxjs/add/observable/from.js
> `

For me it is a problem with resolving paths on local drive.

**Comment by hongbo-miao** [comment]
After updating from v1.0.17 to v1.0.18,
I am having same issue 

> No provider for NgModel

on both `TYPEAHEAD_DIRECTIVES` and `ButtonRadioDirective`.

**Comment by Dinistro** [comment]
@orkisz Sorry, I forgot to write you back :(. This should now be fixed in the newest version (`1.0.20`).

**Comment by orkisz** [comment]
@Dinistro Works like a charm. Thank you!

**Comment by Dinistro** [comment]
@mshahin364 This should be fixed now.

**Comment by orkisz** [comment]
@Dinistro I have one issue outstanding. Error "**No provider for NgModel**" still occurs in tests, but only when using TestComponentBuilder. Do I need to configure angular's DI somehow?

**Comment by Dinistro** [comment]
@orkisz You also need to enable the new forms in your tests. 

This can be done in the `addProviders()`.

```
provideForms(),
disableDeprecatedForms(),
```

Note: This will change in the next RC of Angular I think.

**Comment by orkisz** [comment]
@Dinistro I added those lines in beforeEachProviders, like:

```
// ...
import { provideForms, disableDeprecatedForms } from '@angular/forms';
// ...

describe('MyComponent', () => {
  beforeEachProviders(() => [
    provideForms(),
    disableDeprecatedForms(),
    MyComponent,
    TestComponentBuilder
  ]);
//  ...
```

It seems to be working fine. Thanks!

**Comment by Dinistro** [comment]
@orkisz beforeEachProviders() is deprecated: https://github.com/angular/angular/commit/40b907a657ec6aeb72d0661707a7842a867ac572

Use 
`beforeEach(() => addProviders([]));`
instead

**Comment by valorkin** [comment]
Thanks @Dinistro ! :)

**Comment by orkisz** [comment]
@Dinistro Thanks! :+1:
